import { mediaDetailsType } from "../types/mediaTypes";

const mediaDetailsData: mediaDetailsType = {
  title: "Rick Astley - Never Gonna Give You Up (Official Music Video)",
  author: "Rick Astley",
  thumbnail: "https://i.ytimg.com/vi_webp/dQw4w9WgXcQ/maxresdefault.webp",
  duration: "213",
  formats: [
    {
      mimeType: 'video/mp4; codecs="avc1.640028"',
      container: "mp4",
      audioBitrate: null,
      quality: "hd1080",
      qualityLabel: "1080p",
      size: 80170781,
    },
    {
      mimeType: 'video/mp4; codecs="av01.0.05M.08"',
      container: "mp4",
      quality: "hd720",
      qualityLabel: "720p",
      size: 15710398,
    },
    {
      mimeType: 'video/mp4; codecs="av01.0.04M.08"',
      container: "mp4",
      quality: "large",
      qualityLabel: "480p",
      size: 8577091,
    },
    {
      mimeType: 'video/mp4; codecs="av01.0.01M.08"',
      container: "mp4",
      quality: "medium",
      qualityLabel: "360p",
      size: 5083621,
    },
    {
      mimeType: 'video/mp4; codecs="avc1.4d4015"',
      container: "mp4",
      audioBitrate: null,
      quality: "small",
      qualityLabel: "240p",
      size: 3020923,
    },
    {
      mimeType: 'video/mp4; codecs="avc1.4d400c"',
      container: "mp4",
      audioBitrate: null,
      quality: "tiny",
      qualityLabel: "144p",
      size: 1864273,
    },
    {
      mimeType: 'audio/mp4; codecs="mp4a.40.2"',
      container: "mp4",
      audioBitrate: 128,
      quality: "tiny",
      qualityLabel: null,
      size: 3433605,
    },
    {
      mimeType: 'video/webm; codecs="vp9"',
      container: "webm",
      audioBitrate: null,
      quality: "hd1080",
      qualityLabel: "1080p",
      size: 41148795,
    },
    {
      mimeType: 'video/webm; codecs="vp9"',
      container: "webm",
      audioBitrate: null,
      quality: "hd720",
      qualityLabel: "720p",
      size: 15360749,
    },
    {
      mimeType: 'video/webm; codecs="vp9"',
      container: "webm",
      audioBitrate: null,
      quality: "large",
      qualityLabel: "480p",
      size: 9353813,
    },
    {
      mimeType: 'video/webm; codecs="vp9"',
      container: "webm",
      audioBitrate: null,
      quality: "medium",
      qualityLabel: "360p",
      size: 6625667,
    },
    {
      mimeType: 'video/webm; codecs="vp9"',
      container: "webm",
      audioBitrate: null,
      quality: "small",
      qualityLabel: "240p",
      size: 3902115,
    },
    {
      mimeType: 'video/webm; codecs="vp9"',
      container: "webm",
      audioBitrate: null,
      quality: "tiny",
      qualityLabel: "144p",
      size: 2405376,
    },
    {
      mimeType: 'audio/webm; codecs="opus"',
      container: "webm",
      audioBitrate: 160,
      quality: "tiny",
      qualityLabel: null,
      size: 3437753,
    },
  ],
};

export { mediaDetailsData };
